CREATE TABLE IF NOT EXISTS confirm_location_seller
    (ID BIGSERIAL PRIMARY KEY NOT NULL,
    SELLER_ID BIGINT NOT NULL,
    LOADER_ID BIGINT NOT NULL,
    CONFIRMIND_ID BIGINT,
    TEXT_ADDRESS TEXT,
    COMMENT_LOADER TEXT,
    PHOTO VARCHAR(50),
    DATE_CONFIRMED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECKED BOOLEAN NOT NULL,
    COMMENT_ADMIN TEXT,
    FOREIGN KEY (SELLER_ID) REFERENCES users(USER_ID),
    FOREIGN KEY (LOADER_ID) REFERENCES users(USER_ID),
    FOREIGN KEY (CONFIRMIND_ID) REFERENCES users(USER_ID)
    );